names:
- hero_icon_ally_1
- hero_icon_ally_2
- hero_icon_ally_3
- hero_icon_ally_4
- hero_icon_ally_5
- hero_icon_enemy_1
- hero_icon_enemy_2
- hero_icon_enemy_3
- hero_icon_enemy_4
- hero_icon_enemy_5
- mvp_badge
- mvp_loss_badge
- medal_gold
- medal_silver
- medal_bronze
- match_type_classic
- match_type_ranked
- match_type_brawl
- match_type_custom
- victory_text
- defeat_text
- kda_display
- gold_amount
- damage_dealt
- damage_taken
- healing_done
- turret_damage
- gpm_display
- participation_rate
- match_duration
- player_name
- player_level
- team_indicator_ally
- team_indicator_enemy
- scoreboard_container
- item_icon_1
- item_icon_2
- item_icon_3
- item_icon_4
- item_icon_5
- item_icon_6
- battle_spell_1
- battle_spell_2
- role_indicator
- position_rank
- savage_indicator
- maniac_indicator
- legendary_indicator
- ui_complete
- text_readable
- icons_clear
nc: 51
path: /Users/lesz/Documents/Project-AI/skillshift-ai/yolo_dataset
test: images/test
train: images/train
val: images/val
